### ISSUE TITLE
Wrong character: 阪/坂

### ISSUE THREAD

**Issue by sgalal** [rime/rime-essay#12]
某些「阪」字應該為「坂」字，例如「達坂城」，誤作「阪」。

**Comment by lotem** [comment]
可能不是錯誤，是遵循OpenCC標準。
這組字收在OpenCC的 [異體字表](https://github.com/BYVoid/OpenCC/blame/master/data/scheme/variant.txt)

**Comment by sgalal** [comment]
是異體字關係，同時也都是標準字。類似「閒」、「間」。
見 OpenCC 羣組裏的討論。
