### ISSUE TITLE
请勿将咨文错敲成諮文

### ISSUE THREAD

**Issue by ShikiSuen** [rime/rime-essay#25]
```
國情咨文	0
國情諮文	459
```
错的给高词频，对的给低词频。这机器分析当真荒谬。
建议砍掉第二行、将第二行的频率给第一行。

**Comment by ShikiSuen** [comment]
https://pedia.cloud.edu.tw/Entry/Detail/?title=%E5%92%A8%E6%96%87

**Comment by LEOYoon-Tsaw** [comment]
重复 #24

**Comment by ShikiSuen** [comment]
@LEOYoon-Tsaw 那个 PR 是我开了这个讨论串之后才推送的。还没被 Merge 怎就关了？

**Comment by lotem** [comment]
本品不採用臺灣用字標準。
直接照搬臺灣來源的詞典不行，需要經過字形轉換再匯入。

**Comment by ShikiSuen** [comment]
@lotem 刚刚的 PR 我就是用你在 WIKI 里面给过的转换表转换过的。
不然的话无法与你预设的八股文相容。

至于咨文，我就 Google 检索了一下。除了咨文以外的其他词都是用諮。
你非要在咨文这个词上认为諮文才是正解的话，请问相关典籍出处是？
